is:
  - headers.acceptJson
  - headers.testScenarioHeader
  - headers.contentTypeJson
  - errors.formatNino
  - errors.incorrectOrEmptyBody
  - errors.formatDeductionFromDate
  - errors.formatDeductionToDate
  - errors.ruleDeductionAmount
  - errors.formatFromDate
  - errors.formatToDate
  - errors.ruleCostOfMaterials
  - errors.ruleGrossAmountPaid
  - errors.ruleDateRangeInvalid
  - errors.ruleDeductionsDateRangeInvalid
  - errors.rangeDeductionToDateBeforeDeductionsFromDate
  - errors.clientOrAgentNotAuthorised
  - errors.ruleNoChangeLossAmount
  - errors.ruleFromDate
  - errors.ruleToDate
  - errors.formatSubmissionId
displayName: AMEND CIS Deductions for Subcontractor [test only]
description: This endpoint allows a developer to amend a CIS deductions which has been previously populated.
(annotations.sandboxData): !include scenarios/amend_scenarios.md
(annotations.scope): "write:self-assessment"
securedBy: [ sec.oauth_2_0: { scopes: [ "write:self-assessment" ] } ]
body:
  application/json:
    type: !include schemas/amendCisDeductions/amend_cis_deductions_request.json
    examples:
     example-1:
      description: Amend CIS request
      value: !include examples/create_request.json
responses:
  204:
    headers:
      X-CorrelationId:
        example: c75f40a6-a3df-4429-a697-471eeec46435
        description: Unique ID for operation tracking <br> String, 36 characters.
