#%RAML 1.0
---
title: CIS Deductions (MTD)
description:
version: 1.0

protocols: [ HTTPS ]
baseUri: https://api.service.hmrc.gov.uk/

documentation:
 - title: Overview
   content: !include docs/overview.md
 - title: Versioning
   content: !include https://developer.service.hmrc.gov.uk/api-documentation/assets/common/docs/versioning.md
 - title: Errors
   content: !include docs/errors.md
 - title: Changelog
   content: !include docs/changelog.md
 - title: Support
   content: !include docs/support.md
 - title: Testing
   content: !include docs/testing.md

mediaType: application/hal+json

uses:
  sec: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/securitySchemes.raml
  annotations: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/annotations.raml
  types: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/types.raml
  errors: errors.raml
  headers: headers.raml
  queryParameters: queryParameters.raml

'/individuals/deductions/cis':
  /{nino}:
    uriParameters:
      nino:
        description: 'National Insurance number in the format AA999999A.'
        type: string
        example: TC663795B
    /current-position:
      get: !include list.raml
    /amendments:
      post: !include create.raml
    /amendments/{submissionId}:
        delete: !include delete.raml
        put: !include amend.raml
        uriParameters:
         nino:
           description: 'National Insurance number in the format AA999999A.'
           type: string
           example: TC663795B
         submissionId:
            description: 'A unique identifier for the customer provided CIS deduction amendment.'
            type: string
            example: 4557ecb5-fd32-48cc-81f5-e6acd1099f3c
