#%RAML 1.0
---
title: CIS Deductions (MTD)
description:
version: 1.0

protocols: [ HTTPS ]
baseUri: https://api.service.hmrc.gov.uk/

documentation:
 - title: Overview
   content: !include docs/overview.md
 - title: Changelog
   content: !include docs/changelog.md
 - title: Support
   content: !include docs/support.md
 - title: Testing
   content: !include docs/testing.md
 - title: Versioning
   content: !include https://developer.service.hmrc.gov.uk/api-documentation/assets/common/docs/versioning.md
 - title: Errors
   content: !include https://developer.service.hmrc.gov.uk/api-documentation/assets/common/docs/errors.md

mediaType: application/hal+json

uses:
  sec: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/securitySchemes.raml
  annotations: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/annotations.raml
  types: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/types.raml
  errors: errors.raml
  headers: headers.raml
  queryParameters: queryParameters.raml

'/deductions/cis':
  /{nino}:
    uriParameters:
      nino:
        description: 'National Insurance number in the format AA999999A.'
        type: string
        example: TC663795B
    /amendments:
      post: !include create.raml
    /current-position:
      get: !include list.raml
    /amendments/{id}:
        delete: !include delete.raml
        put: !include amend.raml
        uriParameters:
          id:
           description: 'Unique identifier for the CIS deduction.'
           type: string
           example: S4636A77V5KB8625U
