is:
  - headers.acceptJson
  - headers.testScenarioHeader
  - headers.contentTypeJson
  - errors.formatNino
  - errors.formatSubmissionId
  - errors.clientOrAgentNotAuthorised
  - errors.notFound
displayName: Delete CIS Deductions for Subcontractor
description: This endpoint allows a developer to remove a customer’s CIS deductions data that has been previously populated. A National Insurance number and submission ID must be provided.
(annotations.sandboxData): !include scenarios/delete_scenarios.md
(annotations.scope): "write:self-assessment"
securedBy: [ sec.oauth_2_0: { scopes: [ "write:self-assessment" ] } ]
responses:
  204:
    headers:
      X-CorrelationId:
        example: a1e8057e-fbbc-47a8-a8b4-78d9f015c253
        description: Unique ID for operation tracking <br> String, 36 characters.
