#%RAML 1.0 Library

uses:
  types: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/types.raml


traits:
  notFound:
    responses:
      404:
        body:
          application/json:
            type: types.errorResponse
            example:
              description: The remote endpoint has indicated that no data can be found for the given period.
              value:
                code: MATCHING_RESOURCE_NOT_FOUND
  notFoundIncomeSource:
    responses:
      404:
        body:
          application/json:
            type: types.errorResponse
            example:
              description: The remote endpoint has indicated that the given income source could not be found
              value:
                code: MATCHING_RESOURCE_NOT_FOUND
  notFoundNino:
    responses:
      404:
        body:
          application/json:
            type: types.errorResponse
            example:
              description: The remote endpoint has indicated that no data can be found for the given NINO
              value:
                code: MATCHING_RESOURCE_NOT_FOUND
  notFoundLossId:
    responses:
      404:
        body:
          application/json:
            type: types.errorResponse
            example:
              description: The remote endpoint has indicated that no data can be found for the given loss ID
              value:
                code: MATCHING_RESOURCE_NOT_FOUND
  notFoundClaimId:
    responses:
      404:
        body:
          application/json:
            type: types.errorResponse
            example:
              description: The remote endpoint has indicated that no data can be found for the given claim ID
              value:
                code: MATCHING_RESOURCE_NOT_FOUND
  clientOrAgentNotAuthorised:
    responses:
      403:
        body:
          application/json:
            type: types.errorResponse
            examples:
              clientOrAgentNotAuthorised:
                description: 'The client or agent is not authorised. This is because: the client is not subscribed to MTD, the agent is not subscribed to Agent Services, or the client has not authorised the agent to act on their behalf'
                value:
                  code: CLIENT_OR_AGENT_NOT_AUTHORISED
  formatNino:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              formatNino:
                description: The format of the supplied NINO field is not valid
                value:
                  code: FORMAT_NINO
  formatSubmissionId:
      responses:
        400:
          body:
            application/json:
              type: types.errorResponse
              examples:
                formatSubmissionId:
                  description: The format of the submission ID is not valid.
                  value:
                    code: FORMAT_SUBMISSION_ID
  formatTaxYear:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              formatTaxYear:
                description: The format of the supplied tax year field is not valid
                value:
                  code: FORMAT_TAX_YEAR
  incorrectOrEmptyBody:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              incorrectOrEmptyBody:
                description: An empty or non-matching body was submitted
                value:
                  code: RULE_INCORRECT_OR_EMPTY_BODY_SUBMITTED
  formatDeductionFromDate:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              formatDeductionFromDate:
                description: The deductions From date is not a valid date format
                value:
                  code: FORMAT_DEDUCTION_FROM_DATE
  formatDeductionToDate:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              formatDeductionToDate:
                description: The deductions To date is not a valid date format
                value:
                  code: FORMAT_DEDUCTION_TO_DATE
  ruleDeductionAmount:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              ruleDeductionAmount:
                description: The deduction amount should be a positive number less than 99999999999.99 up to 2 decimal places.
                value:
                  code: RULE_DEDUCTIONS_AMOUNT
  formatFromDate:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              formatFromDate:
                description: The From date is not a valid ISO format date
                value:
                  code: FORMAT_FROM_DATE
  formatToDate:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              formatToDate:
                description: The To date is not a valid ISO format date
                value:
                  code: FORMAT_TO_DATE
  ruleCostOfMaterials:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              ruleCostOfMaterials:
                description: The cost of materials should be a positive number less than 99999999999.99  up to 2 decimal places
                value:
                  code: RULE_COST_OF_MATERIALS
  ruleGrossAmountPaid:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              ruleGrossAmountPaid:
                description: The gross amount should be a positive number less than 99999999999.99 up to 2 decimal places
                value:
                  code: RULE_GROSS_AMOUNT_PAID
  ruleDateRangeInvalid:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              ruleDateRangeInvalid:
                description: The date range is outside a tax year
                value:
                  code: RULE_DATE_RANGE_INVALID
  ruleDeductionsDateRangeInvalid:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              ruleDeductionsDateRangeInvalid:
                description: The deductions period must align from the 6th of one month to the 5th of the following month
                value:
                  code: RULE_DEDUCTIONS_DATE_RANGE_INVALID
  rangeDeductionToDateBeforeDeductionsFromDate:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              rangeDeductionToDateBeforeDeductionsFromDate:
                description: The deductions To date must be after the Deductions From date
                value:
                  code: RANGE_DEDUCTIONS_TO_DATE_BEFORE_DEDUCTIONS_FROM_DATE
  ruleTaxYearNotSupported:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              rule_TaxYearNotSupported:
                description: The specified tax year is not supported. That is, the tax year specified is before the minimum tax year value.
                value:
                  code: RULE_TAX_YEAR_NOT_SUPPORTED
  ruleTaxYearRangeExceeded:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              ruleTaxYearRangeExceeded:
                description: Tax year range exceeded. A tax year range of one year is required.
                value:
                  code: RULE_TAX_YEAR_RANGE_EXCEEDED
  ruleTaxYearNotEnded:
      responses:
        400:
          body:
            application/json:
              type: types.errorResponse
              examples:
                ruleTaxYearNotEnded:
                  description: A brought forward loss is entered before the end of the tax year in which it was generated.
                  value:
                    code: RULE_TAX_YEAR_NOT_ENDED
  ruleNoChangeTypeOfClaim:
    responses:
      403:
        body:
          application/json:
            type: types.errorResponse
            examples:
              ruleNoChangeTypeOfClaim:
                description: The remote endpoint has indicated that the requested type of claim is already active.
                value:
                  code: RULE_ALREADY_EXISTS
  formatLossType:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              formatLossType:
                description: The format of the loss type is not valid.
                value:
                  code: FORMAT_TYPE_OF_LOSS
  formatSelfEmploymentId:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              formatSelfEmploymentId:
                description: The format of the self-employment ID is not valid.
                value:
                  code: FORMAT_SELF_EMPLOYMENT_ID
  ruleSelfEmploymentId:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              ruleSelfEmploymentId:
                description: A self-employment ID can only be supplied for a self-employment business type
                value:
                  code: RULE_SELF_EMPLOYMENT_ID
  formatLossId:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              formatLossId:
                description: The format of the loss ID is not valid.
                value:
                  code: FORMAT_LOSS_ID
  formatLossAmount:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              formatLossAmount:
                description: The format of the loss amount is not valid.
                value:
                  code: FORMAT_LOSS_AMOUNT
  ruleLossAmount:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              ruleLossAmount:
                description: Amounts should be a positive number less than 99999999999.99 with up to 2 decimal places.
                value:
                  code: RULE_LOSS_AMOUNT
  formatTypeOfClaim:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              formatTypeOfClaim:
                description: The format of the type of claim is not valid.
                value:
                  code: FORMAT_TYPE_OF_CLAIM
  ruleTypeOfClaim400:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              ruleTypeOfClaim:
                description: The type of claim supplied is not valid.
                value:
                  code: RULE_TYPE_OF_CLAIM_INVALID
  ruleTypeOfClaim403:
    responses:
      403:
        body:
          application/json:
            type: types.errorResponse
            examples:
              ruleTypeOfClaim:
                description: The type of claim supplied is not valid.
                value:
                  code: RULE_TYPE_OF_CLAIM_INVALID
  rulePeriodNotEnded:
    responses:
      403:
        body:
          application/json:
            type: types.errorResponse
            examples:
              rulePeriodNotEnded:
                description: The loss claim has been made too soon.
                value:
                  code: RULE_PERIOD_NOT_ENDED
  formatClaimId:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              formatClaimId:
                description: The format of the supplied claim ID is not valid.
                value:
                  code: FORMAT_CLAIM_ID
  ruleDuplicateSubmission:
    responses:
      403:
        body:
          application/json:
            type: types.errorResponse
            examples:
              ruleDuplicateSubmission:
                description: A brought forward loss already exists for this income source.
                value:
                  code: RULE_DUPLICATE_SUBMISSION
  ruleDuplicateClaimSubmission:
    responses:
      403:
        body:
          application/json:
            type: types.errorResponse
            examples:
              ruleDuplicateSubmission:
                description: The type of claim is the same as a previous submission.
                value:
                  code: RULE_DUPLICATE_SUBMISSION
  ruleDeleteAfterCrystallisation:
    responses:
      403:
        body:
          application/json:
            type: types.errorResponse
            examples:
              ruleDeleteAfterCrystallisation:
                description: An existing brought forward loss cannot be deleted after it has been crystallised.  The requested resource is locked.
                value:
                  code: RULE_DELETE_AFTER_CRYSTALLISATION
  ruleNoChangeLossAmount:
    responses:
      403:
        body:
          application/json:
            type: types.errorResponse
            examples:
              ruleNoChangeLossAmount:
                description: The loss amount supplied is the same as the existing stored loss amount.
                value:
                  code: RULE_NO_CHANGE
  ruleNoAccountingPeriod:
    responses:
      403:
        body:
          application/json:
            type: types.errorResponse
            examples:
              ruleNoAccountingPeriod:
                description: There is no accounting period for the year of the claim.
                value:
                  code: RULE_NO_ACCOUNTING_PERIOD
  missingFromDate:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              missingFromDate:
                description: The From date parameter is missing
                value:
                  code: MISSING_FROM_DATE
  missingToDate:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              missingToDate:
                description: The To date parameter is missing
                value:
                  code: MISSING_TO_DATE
  ruleSourceInvalid:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              ruleSourceInvalid:
                description: The source of data should be one of these All (Blended view), Customer or Contractor
                value:
                  code: RULE_SOURCE_INVALID
  ruleFromDate:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              ruleFromDate:
                description: The from date is not the start of the tax year
                value:
                  code: RULE_FROM_DATE
  ruleToDate:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              ruleToDate:
                description: The to date is not the end of the tax year
                value:
                  code: RULE_TO_DATE
  formatCisSubmissionID:
     responses:
        400:
          body:
            application/json:
              type: types.errorResponse
              examples:
                formatCisSubmissionID:
                  description: The format of the CIS deduction submission ID is not valid
                  value:
                    code: FORMAT_CIS_SUBMISSION_ID