#%RAML 1.0 Library

uses:
  types: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/types.raml


traits:
  notFound:
    responses:
      404:
        body:
          application/json:
            type: types.errorResponse
            example:
              description: The remote endpoint has indicated that no data can be found for the given period.
              value:
                code: MATCHING_RESOURCE_NOT_FOUND
  notFoundNino:
    responses:
      404:
        body:
          application/json:
            type: types.errorResponse
            example:
              description: The remote endpoint has indicated that no data can be found for the given NINO
              value:
                code: MATCHING_RESOURCE_NOT_FOUND
  clientOrAgentNotAuthorised:
    responses:
      403:
        body:
          application/json:
            type: types.errorResponse
            examples:
              clientOrAgentNotAuthorised:
                description: 'The client or agent is not authorised. This is because: the client is not subscribed to MTD, the agent is not subscribed to Agent Services, or the client has not authorised the agent to act on their behalf'
                value:
                  code: CLIENT_OR_AGENT_NOT_AUTHORISED
  formatNino:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              formatNino:
                description: The format of the supplied NINO field is not valid
                value:
                  code: FORMAT_NINO
  formatSubmissionId:
      responses:
        400:
          body:
            application/json:
              type: types.errorResponse
              examples:
                formatSubmissionId:
                  description: The format of the submission ID is not valid.
                  value:
                    code: FORMAT_SUBMISSION_ID
  formatEmployerReference:
      responses:
        400:
          body:
            application/json:
              type: types.errorResponse
              examples:
                formatSubmissionId:
                  description: The format of the Employer Reference number is invalid
                  value:
                    code: FORMAT_EMPLOYER_REFERENCE
  formatTaxYear:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              formatTaxYear:
                description: The format of the supplied tax year field is not valid
                value:
                  code: FORMAT_TAX_YEAR
  incorrectOrEmptyBody:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              incorrectOrEmptyBody:
                description: An empty or non-matching body was submitted
                value:
                  code: RULE_INCORRECT_OR_EMPTY_BODY_SUBMITTED
  formatDeductionsFromDate:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              formatDeductionsFromDate:
                description: The deductions From date is not a valid date format
                value:
                  code: FORMAT_DEDUCTIONS_FROM_DATE
  formatDeductionsToDate:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              formatDeductionsToDate:
                description: The deductions To date is not a valid date format
                value:
                  code: FORMAT_DEDUCTIONS_TO_DATE
  ruleDeductionsAmount:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              ruleDeductionsAmount:
                description: The deductions amount should be a positive number less than 99999999999.99 up to 2 decimal places.
                value:
                  code: RULE_DEDUCTIONS_AMOUNT
  formatFromDate:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              formatFromDate:
                description: The From date is not a valid format
                value:
                  code: FORMAT_FROM_DATE
  formatToDate:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              formatToDate:
                description: The To date is not a valid format
                value:
                  code: FORMAT_TO_DATE
  ruleCostOfMaterials:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              ruleCostOfMaterials:
                description: The cost of materials should be a positive number less than 99999999999.99  up to 2 decimal places
                value:
                  code: RULE_COST_OF_MATERIALS
  ruleGrossAmountPaid:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              ruleGrossAmountPaid:
                description: The gross amount should be a positive number less than 99999999999.99 up to 2 decimal places
                value:
                  code: RULE_GROSS_AMOUNT_PAID
  ruleDateRangeInvalid:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              ruleDateRangeInvalid:
                description: The specified date range is invalid
                value:
                  code: RULE_DATE_RANGE_INVALID
  ruleDeductionsDateRangeInvalid:
    responses:
      403:
        body:
          application/json:
            type: types.errorResponse
            examples:
              ruleDeductionsDateRangeInvalid:
                description: The deductions period must align from the 6th of one month to the 5th of the following month
                value:
                  code: RULE_DEDUCTIONS_DATE_RANGE_INVALID
  rangeDeductionsToDateBeforeDeductionsFromDate:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              rangeDeductionsToDateBeforeDeductionsFromDate:
                description: The deductions To date must be after the Deductions From date
                value:
                  code: RANGE_DEDUCTIONS_TO_DATE_BEFORE_DEDUCTIONS_FROM_DATE
  ruleTaxYearNotEnded:
      responses:
        403:
          body:
            application/json:
              type: types.errorResponse
              examples:
                ruleTaxYearNotEnded:
                  description: The submission has been made before the tax year has ended
                  value:
                    code: RULE_TAX_YEAR_NOT_ENDED
  ruleDuplicateSubmission:
    responses:
      403:
        body:
          application/json:
            type: types.errorResponse
            examples:
              ruleDuplicateSubmission:
                description: CIS deductions already exists for this tax year
                value:
                  code: RULE_DUPLICATE_SUBMISSION
  missingFromDate:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              missingFromDate:
                description: The From date parameter is missing
                value:
                  code: MISSING_FROM_DATE
  missingToDate:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              missingToDate:
                description: The To date parameter is missing
                value:
                  code: MISSING_TO_DATE
  ruleSourceInvalid:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              ruleSourceInvalid:
                description: The source of data should be one of these All (Blended view), Customer or Contractor
                value:
                  code: RULE_SOURCE_INVALID
  ruleFromDate:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              ruleFromDate:
                description: The from date is not the start of the tax year
                value:
                  code: RULE_FROM_DATE
  ruleToDate:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              ruleToDate:
                description: The to date is not the end of the tax year
                value:
                  code: RULE_TO_DATE
  formatCisSubmissionID:
     responses:
        400:
          body:
            application/json:
              type: types.errorResponse
              examples:
                formatCisSubmissionID:
                  description: The format of the CIS deductions submission ID is not valid
                  value:
                    code: FORMAT_CIS_SUBMISSION_ID
  ruleUnalignedDeductionsPeriod:
     responses:
        403:
         body:
           application/json:
             type: types.errorResponse
             examples:
               ruleUnalignedDeductionsPeriod:
                 description: The deductions periods do not align with the tax year supplied
                 value:
                   code: RULE_UNALIGNED_DEDUCTIONS_PERIOD
  ruleDuplicatePeriod:
    responses:
      403:
        body:
          application/json:
            type: types.errorResponse
            examples:
              ruleDuplicatePeriod:
                description: More than one deduction period has been supplied for the same month or period
                value:
                  code: RULE_DUPLICATE_PERIOD