is:
  - headers.acceptJson
  - headers.testScenarioHeader
  - headers.contentTypeJson
  - errors.formatNino
  - errors.notFoundNino
  - errors.ruleDateRangeInvalid
  - errors.clientOrAgentNotAuthorised
  - errors.formatFromDate
  - errors.missingFromDate
  - errors.formatToDate
  - errors.missingToDate
  - errors.ruleSourceInvalid
  - errors.ruleFromDate
  - errors.ruleToDate
  - queryParameters.from
  - queryParameters.to
  - queryParameters.source
displayName: Retrieve all CIS Deductions for Subcontractor [test only]
description: This endpoint allows a developer to retrieve a list of CIS deductions for subcontractors that have been previously populated.
(annotations.sandboxData): !include scenarios/list_scenarios.md
(annotations.scope): "read:self-assessment"
securedBy: [ sec.oauth_2_0: { scopes: [ "read:self-assessment" ] } ]
responses:
  200:
    body:
      application/json:
        type: !include schemas/list_response.json
        example: !include examples/list_response_1.json
    headers:
      X-CorrelationId:
        example: c75f40a6-a3df-4429-a697-471eeec46435
        description: Unique ID for operation tracking <br> String, 36 characters.
