is:
  - headers.acceptJson
  - headers.testScenarioHeader
  - headers.contentTypeJson
  - errors.notFoundNino
  - errors.formatNino
  - errors.clientOrAgentNotAuthorised
  - errors.formatFromDate
  - errors.missingFromDate
  - errors.formatToDate
  - errors.missingToDate
  - errors.ruleSourceInvalid
  - errors.ruleFromDate
  - errors.ruleToDate
  - queryParameters.from
  - queryParameters.to
  - queryParameters.source
displayName: List all CIS Deductions for Subcontractor [test only]
description: This endpoint allows a developer to retrieve a list of CIS deductions for subcontractors that have been previously populated.
(annotations.sandboxData): !include scenarios/list_scenarios.md
(annotations.scope): "write:self-assessment"
securedBy: [ sec.oauth_2_0: { scopes: [ "write:self-assessment" ] } ]