#%RAML 1.0 Library

uses:
  types: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/types.raml

traits:
  from:
    queryParameters:
      fromDate:
        description: 'The CIS start date of a tax year.<br><br> Date in the format: YYYY-MM-DD'
        example: "2019-04-06"
        required: true
  to:
    queryParameters:
      toDate:
        description: 'The CIS end date of a tax year.<br><br> Date in the format: YYYY-MM-DD'
        example: "2020-04-05"
        required: true
  source:
    queryParameters:
      source:
        description: 'Any source of amended data.'
        example: 'customer'
        required: false