#%RAML 1.0 Library

uses:
  types: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/types.raml

traits:
  from:
    queryParameters:
      fromDate:
        description: 'CIS tax year start date.<br><br> Date in the format: YYYY-MM-DD'
        example: "2020-04-06"
        required: true
  to:
    queryParameters:
      toDate:
        description: 'CIS tax year end date.<br><br> Date in the format: YYYY-MM-DD'
        example: "2021-04-05"
        required: true
  source:
    queryParameters:
      source:
        description: 'The source of amended data. Defaults to `all`. Limited to the following possible values: <b><ul><li>`all`<li>`contractor`<li>`customer`</b>'
        required: false